name: Build Release Artifacts
on:
  release:
    types: [created]
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build-dmg:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - uses: DeLaGuardo/setup-clojure@3.1
        with:
          tools-deps: '1.10.2.774'
      - run: clojure -Spom
      - run: clojure -X:depstar
      - run: jpackage @jpackage/ui @jpackage/macos --app-version ${{  github.event.release.tag_name }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: rock-n-call-ui-${{ github.event.release.tag_name }}.dmg
          asset_name: rock-n-call-ui-${{ github.event.release.tag_name }}.dmg
          asset_content_type: application/x-apple-diskimage
