name: Build Release Artifacts
on:
  - push

env:
  RELEASE_VERSION: "1.2.3"
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build-dmg:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - uses: DeLaGuardo/setup-clojure@3.1
        with:
          tools-deps: '1.10.2.774'
      - run: clojure -Spom
      - run: clojure -X:depstar
      - run: jpackage @jpackage/ui @jpackage/macos --app-version "${RELEASE_VERSION}"
      - run: ls -al
